/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "passkey.login-options": [],
    "passkey.login": [],
    "passkey.confirm-options": [],
    "passkey.confirm": [],
    "passkey.registration-options": [],
    "passkey.store": [],
    "passkey.destroy": [
        {
            "name": "passkey",
            "required": true,
            "binding": "id"
        }
    ],
    "home": [],
    "scanner": [],
    "api.scanner.poll": [
        {
            "name": "session",
            "required": true
        }
    ],
    "api.scanner.submit": [],
    "midtrans.webhook": [],
    "kiosk.show": [
        {
            "name": "token",
            "required": true
        }
    ],
    "kiosk.orders": [
        {
            "name": "token",
            "required": true
        }
    ],
    "kiosk.api.orders.store": [
        {
            "name": "token",
            "required": true
        }
    ],
    "kiosk.api.orders.show": [
        {
            "name": "token",
            "required": true
        },
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "kiosk.api.auth.register": [
        {
            "name": "token",
            "required": true
        }
    ],
    "kiosk.api.auth.login": [
        {
            "name": "token",
            "required": true
        }
    ],
    "kiosk.api.auth.logout": [
        {
            "name": "token",
            "required": true
        }
    ],
    "dashboard": [],
    "pos": [],
    "kitchen": [],
    "orders": [],
    "reports": [],
    "reports.orders": [],
    "payroll.index": [],
    "payroll.export-list": [],
    "payroll.export-report": [],
    "payroll.create": [],
    "payroll.generate": [],
    "payroll.show": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.export": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.update": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.approve": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.pay": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "payroll.destroy": [
        {
            "name": "payroll",
            "required": true,
            "binding": "id"
        }
    ],
    "catalog.menu": [],
    "catalog.categories": [],
    "catalog.packages": [],
    "catalog.add-ons": [],
    "catalog.promos": [],
    "catalog.recipe-book": [],
    "ops.tables": [],
    "ops.inventory": [],
    "ops.inventory-categories": [],
    "ops.inventory-ins": [],
    "ops.inventory-outs": [],
    "ops.inventory-opnames": [],
    "ops.inventory-mutations": [],
    "ops.ingredients": [],
    "ops.ingredient-categories": [],
    "ops.ingredient-batches": [],
    "ops.ingredient-mutations": [],
    "ops.expenses": [],
    "team.employees": [],
    "team.positions": [],
    "team.users": [],
    "team.roles-permissions": [],
    "site-settings.ip-location.edit": [],
    "site-settings.ip-location.update": [],
    "site-settings.database.edit": [],
    "site-settings.database.backup": [],
    "site-settings.database.reset": [],
    "attendance.index": [],
    "attendance.kiosk": [],
    "attendance.store": [],
    "api.menu-items.bulk-delete": [],
    "api.menu-items.bulk-restore": [],
    "api.menu-items.bulk-force": [],
    "api.menu-items.restore": [
        {
            "name": "menu_item",
            "required": true
        }
    ],
    "api.menu-items.force": [
        {
            "name": "menu_item",
            "required": true
        }
    ],
    "api.tables.bulk-delete": [],
    "api.tables.bulk-restore": [],
    "api.tables.bulk-force": [],
    "api.tables.restore": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tables.force": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.bulk-delete": [],
    "api.packages.bulk-restore": [],
    "api.packages.bulk-force": [],
    "api.packages.restore": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.force": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.bulk-delete": [],
    "api.categories.bulk-restore": [],
    "api.categories.bulk-force": [],
    "api.categories.restore": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.force": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.inventory-categories.bulk-delete": [],
    "api.inventory-categories.bulk-restore": [],
    "api.inventory-categories.bulk-force": [],
    "api.inventory-categories.restore": [
        {
            "name": "inventory_category",
            "required": true
        }
    ],
    "api.inventory-categories.force": [
        {
            "name": "inventory_category",
            "required": true
        }
    ],
    "api.inventory-items.bulk-delete": [],
    "api.inventory-items.bulk-restore": [],
    "api.inventory-items.bulk-force": [],
    "api.inventory-items.restore": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-items.force": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-ins.bulk-delete": [],
    "api.inventory-ins.bulk-restore": [],
    "api.inventory-ins.bulk-force": [],
    "api.inventory-ins.restore": [
        {
            "name": "inventory_in",
            "required": true
        }
    ],
    "api.inventory-ins.force": [
        {
            "name": "inventory_in",
            "required": true
        }
    ],
    "api.inventory-outs.bulk-delete": [],
    "api.inventory-outs.bulk-restore": [],
    "api.inventory-outs.bulk-force": [],
    "api.inventory-outs.restore": [
        {
            "name": "inventory_out",
            "required": true
        }
    ],
    "api.inventory-outs.force": [
        {
            "name": "inventory_out",
            "required": true
        }
    ],
    "api.inventory-opnames.bulk-delete": [],
    "api.inventory-opnames.bulk-restore": [],
    "api.inventory-opnames.bulk-force": [],
    "api.inventory-opnames.restore": [
        {
            "name": "inventory_opname",
            "required": true
        }
    ],
    "api.inventory-opnames.force": [
        {
            "name": "inventory_opname",
            "required": true
        }
    ],
    "api.ingredient-categories.bulk-delete": [],
    "api.ingredient-categories.bulk-restore": [],
    "api.ingredient-categories.bulk-force": [],
    "api.ingredient-categories.restore": [
        {
            "name": "ingredient_category",
            "required": true
        }
    ],
    "api.ingredient-categories.force": [
        {
            "name": "ingredient_category",
            "required": true
        }
    ],
    "api.ingredients.bulk-delete": [],
    "api.ingredients.bulk-restore": [],
    "api.ingredients.bulk-force": [],
    "api.ingredients.restore": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "api.ingredients.force": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "api.ingredient-batches.bulk-delete": [],
    "api.ingredient-batches.bulk-restore": [],
    "api.ingredient-batches.bulk-force": [],
    "api.ingredient-batches.restore": [
        {
            "name": "ingredient_batch",
            "required": true
        }
    ],
    "api.ingredient-batches.force": [
        {
            "name": "ingredient_batch",
            "required": true
        }
    ],
    "api.ingredient-mutations.bulk-delete": [],
    "api.ingredient-mutations.bulk-restore": [],
    "api.ingredient-mutations.bulk-force": [],
    "api.ingredient-mutations.restore": [
        {
            "name": "ingredient_mutation",
            "required": true
        }
    ],
    "api.ingredient-mutations.force": [
        {
            "name": "ingredient_mutation",
            "required": true
        }
    ],
    "api.employees.bulk-delete": [],
    "api.employees.bulk-restore": [],
    "api.employees.bulk-force": [],
    "api.employees.restore": [
        {
            "name": "employee",
            "required": true
        }
    ],
    "api.employees.force": [
        {
            "name": "employee",
            "required": true
        }
    ],
    "api.positions.bulk-delete": [],
    "api.positions.bulk-restore": [],
    "api.positions.bulk-force": [],
    "api.positions.restore": [
        {
            "name": "position",
            "required": true
        }
    ],
    "api.positions.force": [
        {
            "name": "position",
            "required": true
        }
    ],
    "api.users.bulk-delete": [],
    "api.users.bulk-restore": [],
    "api.users.bulk-force": [],
    "api.users.restore": [
        {
            "name": "user",
            "required": true
        }
    ],
    "api.users.force": [
        {
            "name": "user",
            "required": true
        }
    ],
    "api.add-ons.bulk-delete": [],
    "api.add-ons.bulk-restore": [],
    "api.add-ons.bulk-force": [],
    "api.add-ons.restore": [
        {
            "name": "add_on",
            "required": true
        }
    ],
    "api.add-ons.force": [
        {
            "name": "add_on",
            "required": true
        }
    ],
    "api.promos.bulk-delete": [],
    "api.promos.bulk-restore": [],
    "api.promos.bulk-force": [],
    "api.promos.restore": [
        {
            "name": "promo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.promos.force": [
        {
            "name": "promo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.bulk-delete": [],
    "api.orders.bulk-restore": [],
    "api.orders.bulk-force": [],
    "api.orders.restore": [
        {
            "name": "order",
            "required": true
        }
    ],
    "api.orders.force": [
        {
            "name": "order",
            "required": true
        }
    ],
    "api.transactions.bulk-delete": [],
    "api.transactions.bulk-restore": [],
    "api.transactions.bulk-force": [],
    "api.transactions.restore": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "api.transactions.force": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "api.users.roles": [],
    "api.roles.index": [],
    "api.roles.store": [],
    "api.roles.destroy": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "api.permissions.index": [],
    "api.roles.permissions.sync": [
        {
            "name": "role",
            "required": true,
            "binding": "id"
        }
    ],
    "api.positions.permissions.sync": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.items.sync": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.inventory-items.barcode": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-mutations.store": [],
    "api.inventory-mutations.index": [],
    "api.kitchen.orders": [],
    "api.kitchen.orders.status": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.kitchen.items.status": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "api.kitchen.menu-items": [],
    "api.kitchen.menu-items.toggle": [
        {
            "name": "menuItem",
            "required": true,
            "binding": "id"
        }
    ],
    "api.kitchen.orders.tts-text": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.kitchen.items.tts-text": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.items.add": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.pay": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.items.cancel": [
        {
            "name": "item",
            "required": true,
            "binding": "id"
        }
    ],
    "api.attendances.index": [],
    "api.attendances.store": [],
    "api.attendances.show": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "api.attendances.verify": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "api.attendances.destroy": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "api.attendances.restore": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "api.attendances.force": [
        {
            "name": "attendance",
            "required": true,
            "binding": "id"
        }
    ],
    "api.reports.dashboard": [],
    "api.reports.transactions": [],
    "api.reports.orders": [],
    "api.audit-logs.index": [],
    "api.payrolls.index": [],
    "api.payrolls.report": [],
    "api.payrolls.missing": [],
    "api.tables.qr.generate": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tables.qr.download": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.menu-items.index": [],
    "api.menu-items.store": [],
    "api.menu-items.show": [
        {
            "name": "menu_item",
            "required": true
        }
    ],
    "api.menu-items.update": [
        {
            "name": "menu_item",
            "required": true
        }
    ],
    "api.menu-items.destroy": [
        {
            "name": "menu_item",
            "required": true
        }
    ],
    "api.tables.index": [],
    "api.tables.store": [],
    "api.tables.show": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tables.update": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tables.destroy": [
        {
            "name": "table",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.index": [],
    "api.packages.store": [],
    "api.packages.show": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.update": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.packages.destroy": [
        {
            "name": "package",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.index": [],
    "api.categories.store": [],
    "api.categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.inventory-categories.index": [],
    "api.inventory-categories.store": [],
    "api.inventory-categories.show": [
        {
            "name": "inventory_category",
            "required": true
        }
    ],
    "api.inventory-categories.update": [
        {
            "name": "inventory_category",
            "required": true
        }
    ],
    "api.inventory-categories.destroy": [
        {
            "name": "inventory_category",
            "required": true
        }
    ],
    "api.inventory-items.index": [],
    "api.inventory-items.store": [],
    "api.inventory-items.show": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-items.update": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-items.destroy": [
        {
            "name": "inventory_item",
            "required": true
        }
    ],
    "api.inventory-ins.index": [],
    "api.inventory-ins.store": [],
    "api.inventory-ins.show": [
        {
            "name": "inventory_in",
            "required": true
        }
    ],
    "api.inventory-ins.update": [
        {
            "name": "inventory_in",
            "required": true
        }
    ],
    "api.inventory-ins.destroy": [
        {
            "name": "inventory_in",
            "required": true
        }
    ],
    "api.inventory-outs.index": [],
    "api.inventory-outs.store": [],
    "api.inventory-outs.show": [
        {
            "name": "inventory_out",
            "required": true
        }
    ],
    "api.inventory-outs.update": [
        {
            "name": "inventory_out",
            "required": true
        }
    ],
    "api.inventory-outs.destroy": [
        {
            "name": "inventory_out",
            "required": true
        }
    ],
    "api.inventory-opnames.index": [],
    "api.inventory-opnames.store": [],
    "api.inventory-opnames.show": [
        {
            "name": "inventory_opname",
            "required": true
        }
    ],
    "api.inventory-opnames.update": [
        {
            "name": "inventory_opname",
            "required": true
        }
    ],
    "api.inventory-opnames.destroy": [
        {
            "name": "inventory_opname",
            "required": true
        }
    ],
    "api.ingredient-categories.index": [],
    "api.ingredient-categories.store": [],
    "api.ingredient-categories.show": [
        {
            "name": "ingredient_category",
            "required": true
        }
    ],
    "api.ingredient-categories.update": [
        {
            "name": "ingredient_category",
            "required": true
        }
    ],
    "api.ingredient-categories.destroy": [
        {
            "name": "ingredient_category",
            "required": true
        }
    ],
    "api.ingredients.index": [],
    "api.ingredients.store": [],
    "api.ingredients.show": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "api.ingredients.update": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "api.ingredients.destroy": [
        {
            "name": "ingredient",
            "required": true,
            "binding": "id"
        }
    ],
    "api.ingredient-batches.index": [],
    "api.ingredient-batches.store": [],
    "api.ingredient-batches.show": [
        {
            "name": "ingredient_batch",
            "required": true
        }
    ],
    "api.ingredient-batches.update": [
        {
            "name": "ingredient_batch",
            "required": true
        }
    ],
    "api.ingredient-batches.destroy": [
        {
            "name": "ingredient_batch",
            "required": true
        }
    ],
    "api.ingredient-mutations.index": [],
    "api.ingredient-mutations.store": [],
    "api.ingredient-mutations.show": [
        {
            "name": "ingredient_mutation",
            "required": true
        }
    ],
    "api.ingredient-mutations.update": [
        {
            "name": "ingredient_mutation",
            "required": true
        }
    ],
    "api.ingredient-mutations.destroy": [
        {
            "name": "ingredient_mutation",
            "required": true
        }
    ],
    "api.employees.index": [],
    "api.employees.store": [],
    "api.employees.show": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "api.employees.update": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "api.employees.destroy": [
        {
            "name": "employee",
            "required": true,
            "binding": "id"
        }
    ],
    "api.positions.index": [],
    "api.positions.store": [],
    "api.positions.show": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "api.positions.update": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "api.positions.destroy": [
        {
            "name": "position",
            "required": true,
            "binding": "id"
        }
    ],
    "api.users.index": [],
    "api.users.store": [],
    "api.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.add-ons.index": [],
    "api.add-ons.store": [],
    "api.add-ons.show": [
        {
            "name": "add_on",
            "required": true
        }
    ],
    "api.add-ons.update": [
        {
            "name": "add_on",
            "required": true
        }
    ],
    "api.add-ons.destroy": [
        {
            "name": "add_on",
            "required": true
        }
    ],
    "api.promos.index": [],
    "api.promos.store": [],
    "api.promos.show": [
        {
            "name": "promo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.promos.update": [
        {
            "name": "promo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.promos.destroy": [
        {
            "name": "promo",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.index": [],
    "api.orders.store": [],
    "api.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.orders.update": [
        {
            "name": "order",
            "required": true
        }
    ],
    "api.orders.destroy": [
        {
            "name": "order",
            "required": true
        }
    ],
    "api.transactions.index": [],
    "api.transactions.store": [],
    "api.transactions.show": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "api.transactions.update": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "api.transactions.destroy": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "security.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
